services:
  php81-fpm:
    container_name: eledock-php81-fpm
    build:
      context: ./php-fpm
      args:
        - ELEDOCK_PHP_VERSION=8.1
        - NON_ROOT_UID=${NON_ROOT_UID}
        - NON_ROOT_GID=${NON_ROOT_GID}
        - ADDITIONAL_PHP_EXTENSIONS=${PHP_81_ADDITIONAL_EXTENSIONS}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/eledock.ini:/usr/local/etc/php/conf.d/eledock.ini
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php-fpm/eledock.pool.conf:/usr/local/etc/php-fpm.d/eledock.pool.conf
    expose:
      - "9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      internal:
        ipv4_address: 10.20.30.81

  php82-fpm:
    container_name: eledock-php82-fpm
    build:
      context: ./php-fpm
      args:
        - ELEDOCK_PHP_VERSION=8.2
        - NON_ROOT_UID=${NON_ROOT_UID}
        - NON_ROOT_GID=${NON_ROOT_GID}
        - ADDITIONAL_PHP_EXTENSIONS=${PHP_82_ADDITIONAL_EXTENSIONS}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/eledock.ini:/usr/local/etc/php/conf.d/eledock.ini
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php-fpm/eledock.pool.conf:/usr/local/etc/php-fpm.d/eledock.pool.conf
    expose:
      - "9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      internal:
        ipv4_address: 10.20.30.82

  php83-fpm:
    container_name: eledock-php83-fpm
    build:
      context: ./php-fpm
      args:
        - ELEDOCK_PHP_VERSION=8.3
        - NON_ROOT_UID=${NON_ROOT_UID}
        - NON_ROOT_GID=${NON_ROOT_GID}
        - ADDITIONAL_PHP_EXTENSIONS=${PHP_83_ADDITIONAL_EXTENSIONS}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/eledock.ini:/usr/local/etc/php/conf.d/eledock.ini
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php-fpm/eledock.pool.conf:/usr/local/etc/php-fpm.d/eledock.pool.conf
    expose:
      - "9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      internal:
        ipv4_address: 10.20.30.83

  php84-fpm:
    container_name: eledock-php84-fpm
    build:
      context: ./php-fpm
      args:
        - ELEDOCK_PHP_VERSION=8.4
        - NON_ROOT_UID=${NON_ROOT_UID}
        - NON_ROOT_GID=${NON_ROOT_GID}
        - ADDITIONAL_PHP_EXTENSIONS=${PHP_83_ADDITIONAL_EXTENSIONS}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/eledock.ini:/usr/local/etc/php/conf.d/eledock.ini
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php-fpm/eledock.pool.conf:/usr/local/etc/php-fpm.d/eledock.pool.conf
    expose:
      - "9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      internal:
        ipv4_address: 10.20.30.84

  nginx:
    container_name: eledock-nginx
    build:
      context: ./nginx
      args:
        - NON_ROOT_UID=${NON_ROOT_UID}
        - NON_ROOT_GID=${NON_ROOT_GID}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${LOG_PATH_HOST}/nginx:/var/log/nginx
      - ${NGINX_HOST_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    depends_on:
      - "php81-fpm"
      - "php82-fpm"
      - "php83-fpm"
      - "php84-fpm"
      - "dnsmasq"
    networks:
      internal:
        ipv4_address: 10.20.30.11

  nodejs:
    container_name: eledock-nodejs
    build:
      context: ./nodejs
      args:
        - NON_ROOT_UID=${NON_ROOT_UID}
        - NON_ROOT_GID=${NON_ROOT_GID}
    environment:
      - DISPLAY
    init: true
    dns: 10.20.30.10
    volumes:
      - ${APP_CODE_PATH_HOST}:/home/node/www
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      internal:
        ipv4_address: 10.20.30.12

  mariadb:
    container_name: eledock-mariadb
    build:
      context: ./mariadb
      args:
        - TZ=${MARIADB_TIME_ZONE}
        - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      internal:
        ipv4_address: 10.20.30.13

  postgres:
    container_name: eledock-postgres
    build:
      context: ./postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${POSTGRES_TIME_ZONE}
    networks:
      internal:
        ipv4_address: 10.20.30.14

  adminer:
    container_name: eledock-adminer
    build:
      context: ./adminer
    volumes:
      - ./adminer/uploads.ini:/etc/php/7.4/fpm/conf.d/0-uploads.ini
    ports:
      - "${ADMINER_HOST_HTTP_PORT}:8080"
    networks:
      internal:
        ipv4_address: 10.20.30.15

  redis:
    container_name: eledock-redis
    build:
      context: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      internal:
        ipv4_address: 10.20.30.16

  redis-webui:
    container_name: eledock-redis-webui
    build:
      context: ./redis-webui
    environment:
      - ADMIN_USER=${REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
    ports:
      - "${REDIS_WEBUI_PORT}:80"
    depends_on:
      - redis
    networks:
      internal:
        ipv4_address: 10.20.30.17

  mailhog:
    container_name: eledock-mailhog
    build:
      context: ./mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      internal:
        ipv4_address: 10.20.30.18

  sftp:
    container_name: eledock-sftp
    build:
      context: ./sftp
    volumes:
      - ./sftp/sftp_key.pub:/home/foo/.ssh/keys/sftp_key.pub
    ports:
      - "2222:22"
    command: foo::::upload
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      internal:
        ipv4_address: 10.20.30.19

  dnsmasq:
    container_name: eledock-dnsmasq
    build:
      context: ./dnsmasq
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    networks:
      internal:
        ipv4_address: 10.20.30.10

networks:
  internal:
    external: false
    ipam:
      config:
        - subnet: 10.20.30.0/24